export type ProductItem = {
  name: string;
  category: string;
  image: string;
  specs: string[];
};

export const productsCatalog: ProductItem[] = [
  {
    name: 'LANYING 3B All-day Plus Combination',
    category: 'Mission / Solution Packages',
    image: '/product_images_cropped/mission_packages/15_bomber_drone_solution.png',
    specs: ['Bomber drone solution', 'Carries 4x 60 mm mortars or 2x 82 mm mortars', 'Visible-light, infrared and laser cameras', 'Day/night bombing and reconnaissance'],
  },
  {
    name: 'LANYING 4B All-day Basic Combination',
    category: 'Mission / Solution Packages',
    image: '/product_images_cropped/mission_packages/15_bomber_drone_solution.png',
    specs: ['Bomber drone solution', 'Multi-rotor platform', 'Carries 4x 60 mm or 2x 82 mm mortar shells', 'Visible-light and infrared cameras'],
  },
  {
    name: 'LANYING 5G Plus Package',
    category: 'Mission / Solution Packages',
    image: '/product_images_cropped/mission_packages/15_integrated_reconnaissance_and_attack_uav_solution.png',
    specs: ['Reconnaissance-and-attack package', 'Triple-camera suite: visible, IR, laser ranging / irradiation', 'Can transmit imagery and target coordinates', 'Can carry multiple 60 mm / 82 mm rounds plus 120 mm shell'],
  },
  {
    name: 'LANYING 3G Plus Combination',
    category: 'Mission / Solution Packages',
    image: '/product_images_cropped/uav_components/15_lanying_3g_plus_combination.png',
    specs: ['Reconnaissance-and-attack package', 'Triple-camera suite: visible, IR, laser ranging / irradiation', 'Can transmit imagery and target coordinates', 'Carries 4x 60 mm or 2x 82 mm mortar shells'],
  },
  {
    name: 'LANYING 3A Plus Combination',
    category: 'Mission / Solution Packages',
    image: '/product_images_cropped/uav_airframes/16_lanying_3a_plus_combination.png',
    specs: ['Reconnaissance package', 'Visible, IR, laser ranging and irradiation payload', 'Transmits image or coordinates to ground station', 'Can guide rear laser-guided weapons'],
  },
  {
    name: 'LANYING 1A Basic Combination',
    category: 'Mission / Solution Packages',
    image: '/product_images_cropped/uav_airframes/16_lanying_1a_basic_combination.png',
    specs: ['Reconnaissance package', 'Visible, IR and laser-ranging camera set', 'Transmits image or target coordinates', 'Long-endurance surveillance role'],
  },
  {
    name: 'LANYING 1',
    category: 'UAV Airframes / Flying Platforms',
    image: '/product_images_cropped/uav_airframes/17_lanying_1_full.png',
    specs: ['All-up weight: 3 kg', 'Wingspan: 1520 mm', 'Max flight time: 160 min', 'Transmission distance: 80 km'],
  },
  {
    name: 'LANYING 3',
    category: 'UAV Airframes / Flying Platforms',
    image: '/product_images_cropped/uav_airframes/17_lanying_3_full.png',
    specs: ['All-up weight: 10 kg', 'Body length: 1899 mm', 'Span: 3914 mm', 'Max flight time: 160 min'],
  },
  {
    name: 'LANYING 4',
    category: 'UAV Airframes / Flying Platforms',
    image: '/product_images_cropped/uav_airframes/20_lanying_4_full.png',
    specs: ['All-up weight: 10 kg', 'Max flight time: 70 min', 'Cruising speed: 15 m/s', 'Transmission distance: 20 km / 30 km'],
  },
  {
    name: 'LANYING 5',
    category: 'UAV Airframes / Flying Platforms',
    image: '/product_images_cropped/uav_airframes/18_lanying_5_full.png',
    specs: ['All-up weight: 20 kg', 'Wingspan: 2580 mm', 'Max flight time: 180 min', 'Transmission distance: 80 km'],
  },
  {
    name: 'LANYING 8',
    category: 'UAV Airframes / Flying Platforms',
    image: '/product_images_cropped/uav_airframes/21_lanying_8_full.png',
    specs: ['All-up weight: 50 kg', 'Max payload: 96 kg', 'Max flight time: 50 min', 'Transmission distance: 20 km / 30 km'],
  },
  {
    name: 'LANYING 12',
    category: 'UAV Airframes / Flying Platforms',
    image: '/product_images_cropped/uav_airframes/22_lanying_12_full.png',
    specs: ['All-up weight: 100 kg', 'Max payload: 200 kg', 'Max flight time: 30 min', 'Transmission distance: 20 km / 30 km'],
  },
  {
    name: 'LANYING M2',
    category: 'UAV Airframes / Flying Platforms',
    image: '/product_images_cropped/uav_airframes/23_lanying_m2_full.png',
    specs: ['Flying-wing loitering / suicide drone', 'Body length: 635 mm', 'Span: 1680 mm', 'Max flight time: 30 min'],
  },
  {
    name: 'Earth Station',
    category: 'Ground Control Stations',
    image: '/product_images_cropped/payloads_and_ground/24_ls1.png',
    specs: ['Battery capacity: 13 Ah', 'Working time: 4 h', 'Operating band: 2.4 GHz', 'Dual-screen control station'],
  },
  {
    name: 'Pan-Tilt Camera LS2',
    category: 'EO / IR Payloads, Gimbals, Cameras',
    image: '/product_images_cropped/payloads_and_ground/24_ls2.png',
    specs: ['Battery: 6900 mAh', 'Working time: 3.5 h', '2.4 GHz link', '5.5 in control screen'],
  },
  {
    name: 'LANYING VT360R',
    category: 'EO / IR Payloads, Gimbals, Cameras',
    image: '/product_images_cropped/payloads_and_ground/24_lanying_vt360r.png',
    specs: ['2-axis gimbal', 'Visible + thermal imaging', '30x optical zoom', '360° pan, -110° to +10° pitch'],
  },
  {
    name: 'LANYING VT360RL',
    category: 'EO / IR Payloads, Gimbals, Cameras',
    image: '/product_images_cropped/payloads_and_ground/24_lanying_vt360rl.png',
    specs: ['2-axis gimbal', 'Visible + thermal + laser ranging / irradiation', '30x optical zoom', 'Laser ranging: 120-5000 m'],
  },
  {
    name: 'LANYING M7',
    category: 'EO / IR Payloads, Gimbals, Cameras',
    image: '/product_images_cropped/payloads_and_ground/26_lanying_m7.png',
    specs: ['3-axis stabilized payload', 'Visible + thermal imaging', '10x optical zoom', 'Weight: 0.8 kg'],
  },
  {
    name: 'LANYING T50',
    category: 'EO / IR Payloads, Gimbals, Cameras',
    image: '/product_images_cropped/payloads_and_ground/26_lanying_t50.png',
    specs: ['3-axis stabilized thermal payload', '50 mm thermal imaging', '640 x 512 IR camera', 'Weight: 0.8 kg'],
  },
  {
    name: 'Wyvern T2',
    category: 'Munition Carriers / Bomb Racks',
    image: '/product_images_cropped/munition_carriers/26_fixed_wing_munition_carrier_1.png',
    specs: ['Fixed-wing munition carrier', 'Automatic and manual delivery', 'Quick shell mounting with safety pin', 'Customizable by shell size'],
  },
  {
    name: 'Wyvern T4',
    category: 'Munition Carriers / Bomb Racks',
    image: '/product_images_cropped/munition_carriers/26_multirotor_towed_munitions_carrier_1.png',
    specs: ['Multirotor munition carrier', '1 / 2 / 4 / 6 / 8 / 16-round versions', 'Supports 60 mm / 82 mm / 120 mm shells', 'Automatic or manual placement'],
  },
  {
    name: 'Wyvern T6',
    category: 'Munition Carriers / Bomb Racks',
    image: '/product_images_cropped/munition_carriers/26_multirotor_towed_munitions_carrier_2.png',
    specs: ['Multirotor munition carrier', '1 / 2 / 4 / 6 / 8 / 16-round versions', 'Supports 60 mm / 82 mm / 120 mm shells', 'Automatic or manual placement'],
  },
  {
    name: 'Wyvern T4M',
    category: 'Munition Carriers / Bomb Racks',
    image: '/product_images_cropped/munition_carriers/15_wyvern_munition_carrier_top.png',
    specs: ['Munition carrier family member', 'Listed in brochure', 'Exact standalone parameter block not fully legible', 'Use page image as visual reference'],
  },
  {
    name: 'Wyvern T6M',
    category: 'Munition Carriers / Bomb Racks',
    image: '/product_images_cropped/munition_carriers/15_wyvern_munition_carrier_bottom.png',
    specs: ['Munition carrier family member', 'Listed in brochure', 'Exact standalone parameter block not fully legible', 'Use page image as visual reference'],
  },
  {
    name: 'LS1 Wyvern Munition Carrier',
    category: 'Munition Carriers / Bomb Racks',
    image: '/product_images_cropped/munition_carriers/15_wyvern_munition_carrier_top.png',
    specs: ['Referenced throughout attack packages', 'Used with VT360R / VT360RL combinations', 'Bomb / shell carrier role', 'Standalone page not clearly legible in OCR'],
  },
  {
    name: 'Handheld Countermeasures (single band)',
    category: 'Anti-drone Jammers / Countermeasure Devices',
    image: '/product_images_cropped/anti_drone_devices/05_handheld_countermeasures_single_band.png',
    specs: ['825-960 MHz', '50 W', '32 x 21.5 x 9 cm', 'Jamming range <= 2 km'],
  },
  {
    name: 'Handheld Countermeasures (3-band)',
    category: 'Anti-drone Jammers / Countermeasure Devices',
    image: '/product_images_cropped/anti_drone_devices/06_handheld_countermeasures_3_band.png',
    specs: ['700-800 / 800-900 / 925-960 MHz', '150 W', '32 x 21.5 x 9 cm', 'Jamming range <= 2 km'],
  },
  {
    name: 'Hand-held gun type anti drone device (6 band)',
    category: 'Anti-drone Jammers / Countermeasure Devices',
    image: '/product_images_cropped/anti_drone_devices/07_hand_held_gun_type_anti_drone_device_6_band.png',
    specs: ['420-450 / 825-960 / 1100-1300 / 1560-1620 / 2400-2500 / 5725-5875 MHz', '160 W', '4.8 kg', 'Directional, <= 2 km'],
  },
  {
    name: 'Hand-held gun type anti drone device (8 band)',
    category: 'Anti-drone Jammers / Countermeasure Devices',
    image: '/product_images_cropped/anti_drone_devices/08_hand_held_gun_type_anti_drone_device_8_band.png',
    specs: ['Adds 1360-1450 and 5150-5300 MHz bands', '180 W', '5 kg', 'Directional, <= 2 km'],
  },
  {
    name: 'Shield type anti drone device',
    category: 'Anti-drone Jammers / Countermeasure Devices',
    image: '/product_images_cropped/anti_drone_devices/09_shield_type_anti_drone_device.png',
    specs: ['Band 6 / Band 8 variants', '140 W', '4.7 kg', 'Directional, <= 2 km'],
  },
  {
    name: 'Backpack type anti drone device (custom, 400 W)',
    category: 'Anti-drone Jammers / Countermeasure Devices',
    image: '/product_images_cropped/anti_drone_devices/10_backpack_type_anti_drone_device_custom_400w.png',
    specs: ['Band 6 / 8 / 12', '400 W', '20 kg', 'Directional / omnidirectional, <= 2.5 km'],
  },
  {
    name: 'Backpack type anti drone device (custom, 300 W)',
    category: 'Anti-drone Jammers / Countermeasure Devices',
    image: '/product_images_cropped/anti_drone_devices/11_backpack_type_anti_drone_device_custom_300w.png',
    specs: ['Band 6 / 8', '300 W', '18 kg', 'Directional / omnidirectional, <= 2 km'],
  },
  {
    name: 'Chassis type anti drone device (custom)',
    category: 'Anti-drone Jammers / Countermeasure Devices',
    image: '/product_images_cropped/anti_drone_devices/12_chassis_type_anti_drone_device_custom.png',
    specs: ['Band 4 / 6 / 8', '400 W', '10 kg', 'AC100-240V / DC24V, <= 2.5 km'],
  },
  {
    name: 'Spherical anti drone device (7 band)',
    category: 'Anti-drone Jammers / Countermeasure Devices',
    image: '/product_images_cropped/anti_drone_devices/13_spherical_anti_drone_device_7_band.png',
    specs: ['450 W', '43 x 43 x 40 cm', 'Omnidirectional', 'Jamming range <= 3 km'],
  },
  {
    name: 'Luggage type anti drone device (custom)',
    category: 'Anti-drone Jammers / Countermeasure Devices',
    image: '/product_images_cropped/anti_drone_devices/15_luggage_type_anti_drone_device_custom_tower.png',
    specs: ['Band 10 / 14 / 16', '800 W', '50 kg', 'Omnidirectional, <= 3 km'],
  },
  {
    name: 'LANYING J1-1500',
    category: 'Anti-drone Jammers / Countermeasure Devices',
    image: '/product_images_cropped/counter_uas_systems/27_lanying_j1_1500.png',
    specs: ['1.5 km handheld gun jammer', 'Removable 7000 mAh battery', 'Forced landing / return', 'Up to 8 channels'],
  },
  {
    name: 'LANYING J4-2000',
    category: 'Anti-drone Jammers / Countermeasure Devices',
    image: '/product_images_cropped/counter_uas_systems/31_lanying_j4_2000.png',
    specs: ['Eight-band omnidirectional jammer', 'Max range: 2 km', '360° interference', 'AC 220 V'],
  },
  {
    name: 'LANYING J6-2000',
    category: 'Anti-drone Jammers / Countermeasure Devices',
    image: '/product_images_cropped/counter_uas_systems/31_lanying_j6_2000.png',
    specs: ['Automatic tracking directional jammer', 'Band: 300 MHz - 6 GHz', 'Max range: 2 km', '6 channels'],
  },
  {
    name: 'Hand-held detection device (0-2 km)',
    category: 'Drone Detection Devices',
    image: '/product_images_cropped/detection_and_jamming_devices/20_hand_held_gun_type_detection_and_jamming_device.png',
    specs: ['300 MHz - 6000 MHz', '50 W', '215 g', 'Detection distance <= 3 km'],
  },
  {
    name: 'Portable detection device',
    category: 'Drone Detection Devices',
    image: '/product_images_cropped/detection_devices/16_handheld_detection_device.png',
    specs: ['Listed in brochure main products', 'Portable detector category', 'Detailed parameter page not clearly legible', 'Uses brochure product image as reference'],
  },
  {
    name: 'Spherical detection device (0-3 km)',
    category: 'Drone Detection Devices',
    image: '/product_images_cropped/detection_devices/17_spherical_detection_device_0_3km.png',
    specs: ['70 MHz - 6000 MHz', '50 W', '11 kg', 'AC220V or built-in battery'],
  },
  {
    name: 'Spherical detection device (0-7 km)',
    category: 'Drone Detection Devices',
    image: '/product_images_cropped/detection_devices/18_spherical_detection_device_0_7km.png',
    specs: ['70 MHz - 6000 MHz', '50 W', '20 kg', 'Positioning and automatic north correction'],
  },
  {
    name: 'Spherical detection device (0-10 km)',
    category: 'Drone Detection Devices',
    image: '/product_images_cropped/detection_devices/19_spherical_detection_device_0_10km.png',
    specs: ['100 MHz - 6 GHz detectable range', 'Direction-finding: 2 GHz - 6 GHz', '20 kg', 'Supports DJI / Autel / FPV / DIY'],
  },
  {
    name: 'D7-10000',
    category: 'Drone Detection Devices',
    image: '/product_images_cropped/counter_uas_systems/28_lanying_d7_10000.png',
    specs: ['Luggage detector', 'Detection range up to 10 km', 'Touch-screen portable system', 'Shows serial, model, position, altitude and track'],
  },
  {
    name: 'Hand-held gun type detection and jamming device',
    category: 'Detection + Jamming Integrated Systems',
    image: '/product_images_cropped/detection_and_jamming_devices/20_hand_held_gun_type_detection_and_jamming_device.png',
    specs: ['Detection: 300 MHz - 6000 MHz', 'Jamming bands: 420-450 / 825-960 / 1100-1300 / 1560-1620 / 2400-2500 / 5725-5875 MHz', '6 kg', 'Directional jam, omnidirectional detect'],
  },
  {
    name: 'Spherical detection and jamming device',
    category: 'Detection + Jamming Integrated Systems',
    image: '/product_images_cropped/detection_and_jamming_devices/21_spherical_detection_and_jamming_device.png',
    specs: ['Detection: 300 MHz - 6000 MHz', 'Jamming range <= 3 km', 'Detection distance <= 3 km', '30 kg'],
  },
  {
    name: 'Luggage detection and jamming device',
    category: 'Detection + Jamming Integrated Systems',
    image: '/product_images_cropped/detection_and_jamming_devices/21_spherical_detection_and_jamming_device.png',
    specs: ['Listed in brochure main products', 'Luggage-format integrated detect / jam product', 'Exact standalone parameter page not clearly legible', 'Uses brochure image as reference'],
  },
  {
    name: 'LANYING DJS10-5000',
    category: 'Detection + Jamming Integrated Systems',
    image: '/product_images_cropped/counter_uas_systems/30_lanying_djs10_5000.png',
    specs: ['Fixed integrated observe / attack / lure unit', 'Detection + jamming + navigation decoy', 'Detection range: 5 km', 'Jamming range: 2 km'],
  },
  {
    name: 'DJS11-5000',
    category: 'Detection + Jamming Integrated Systems',
    image: '/product_images_cropped/counter_uas_systems/30_lanying_djs11_5000.png',
    specs: ['Trolley-bag integrated detection / induction equipment', 'Integrated detect / identify / jam / decoy', 'Navigation decoy range: 5 km', 'Battery-powered portable format'],
  },
  {
    name: 'LANYING DJ9-5000',
    category: 'Detection + Jamming Integrated Systems',
    image: '/product_images_cropped/counter_uas_systems/28_lanying_dj9_5000.png',
    specs: ['Backpack detection and interference integrated equipment', 'All-directional + directional early warning', 'Working time: 10 h', 'Max jamming range: 1500 m'],
  },
  {
    name: 'Fixed decoy device',
    category: 'Drone Decoy / Navigation Spoofing Devices',
    image: '/product_images_cropped/decoy_devices/22_fixed_decoy_device.png',
    specs: ['Supports GPS / Beidou / GLONASS / Galileo', 'Defense mode / no-fly mode / directional drive', 'Decoy distance <= 15 km', '24-hour autonomous operation'],
  },
  {
    name: 'LANYING S8-5000',
    category: 'Drone Decoy / Navigation Spoofing Devices',
    image: '/product_images_cropped/counter_uas_systems/32_lanying_s8_5000.png',
    specs: ['5 km fixed navigation decoy', 'Low-power spoofing < 10 dBm', 'Prevents UAV entry into protected area', 'IP66'],
  },
  {
    name: 'LANYING R20-5000',
    category: 'Radar Systems',
    image: '/product_images_cropped/counter_uas_systems/29_lanying_r20_5000.png',
    specs: ['Three-coordinate radar', 'X-band (9-10.2 GHz)', 'Detection range: 5000 m', 'Can be cascaded with jamming / laser / decoy systems'],
  },
  {
    name: 'LANYING R20-15000',
    category: 'Radar Systems',
    image: '/product_images_cropped/counter_uas_systems/29_lanying_r20_15000.png',
    specs: ['Three-coordinate radar', '15 km class', 'Pulse Doppler radar', 'Target capacity: 200'],
  },
  {
    name: 'VT22-2000',
    category: 'Tracking / Photoelectric Systems',
    image: '/product_images_cropped/counter_uas_systems/29_lanying_vt22_2000.png',
    specs: ['Non-cooling multi-spectral intelligent tracking camera', 'Visible-light + thermal tracking', 'Visible detection >= 5 km', 'Thermal tracking >= 1.5 km'],
  },
];

export const productCategories = [
  'Mission / Solution Packages',
  'UAV Airframes / Flying Platforms',
  'Ground Control Stations',
  'EO / IR Payloads, Gimbals, Cameras',
  'Munition Carriers / Bomb Racks',
  'Anti-drone Jammers / Countermeasure Devices',
  'Drone Detection Devices',
  'Detection + Jamming Integrated Systems',
  'Drone Decoy / Navigation Spoofing Devices',
  'Radar Systems',
  'Tracking / Photoelectric Systems',
] as const;
